os: linux
dist: xenial
language: java
jdk: openjdk8

script: ./gradlew build

deploy:
  provider: releases
  api_key:  
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/**/*
  skip_cleanup: true
  on:
    tags: true
